<?php

namespace App\Support;

/**
 * Hand-curated course stats sourced from UDisc/PDGA, used to fill in the
 * hole count, par, and hole-by-hole detail that OpenStreetMap usually lacks.
 * Matched onto OSM course pins by proximity in CourseController.
 *
 * Each course can have multiple `layouts` (UDisc courses are often played
 * from several different tee/basket configurations, e.g. "AM"/"MPO", short/
 * long, etc). The first layout in the array is treated as the primary one
 * shown by default.
 */
class CuratedCourses
{
    public static function all(): array
    {
        return [
            [
                'name' => 'Priekuļu Disku Golfa Laukums',
                'lat' => 57.31173642011239,
                'lon' => 25.37114515900612,
                'address' => 'Ērgļu gatve 9, Priekuļi, LV-4126, Latvia',
                'locality' => 'Priekuļi',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/priekulu-disku-golfa-laukums-2eAb',
                'layouts' => [
                    [
                        'name' => 'AM 2026',
                        'holes_count' => 18,
                        'par' => 59,
                        'length_ft' => 6689,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 284],
                            ['number' => 2, 'par' => 3, 'length_ft' => 426],
                            ['number' => 3, 'par' => 3, 'length_ft' => 343],
                            ['number' => 4, 'par' => 3, 'length_ft' => 270],
                            ['number' => 5, 'par' => 4, 'length_ft' => 524],
                            ['number' => 6, 'par' => 4, 'length_ft' => 589],
                            ['number' => 7, 'par' => 4, 'length_ft' => 529],
                            ['number' => 8, 'par' => 3, 'length_ft' => 317],
                            ['number' => 9, 'par' => 3, 'length_ft' => 219],
                            ['number' => 10, 'par' => 3, 'length_ft' => 215],
                            ['number' => 11, 'par' => 3, 'length_ft' => 301],
                            ['number' => 12, 'par' => 3, 'length_ft' => 466],
                            ['number' => 13, 'par' => 4, 'length_ft' => 442],
                            ['number' => 14, 'par' => 3, 'length_ft' => 295],
                            ['number' => 15, 'par' => 3, 'length_ft' => 284],
                            ['number' => 16, 'par' => 4, 'length_ft' => 418],
                            ['number' => 17, 'par' => 3, 'length_ft' => 439],
                            ['number' => 18, 'par' => 3, 'length_ft' => 327],
                        ],
                    ],
                    [
                        'name' => 'PRO 2026',
                        'holes_count' => 18,
                        'par' => 60,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 284],
                            ['number' => 2, 'par' => 3, 'length_ft' => 490],
                            ['number' => 3, 'par' => 3, 'length_ft' => 343],
                            ['number' => 4, 'par' => 3, 'length_ft' => 270],
                            ['number' => 5, 'par' => 4, 'length_ft' => 524],
                            ['number' => 6, 'par' => 4, 'length_ft' => 589],
                            ['number' => 7, 'par' => 5, 'length_ft' => 798],
                            ['number' => 8, 'par' => 3, 'length_ft' => 317],
                            ['number' => 9, 'par' => 3, 'length_ft' => 327],
                            ['number' => 10, 'par' => 3, 'length_ft' => 215],
                            ['number' => 11, 'par' => 3, 'length_ft' => 301],
                            ['number' => 12, 'par' => 3, 'length_ft' => 466],
                            ['number' => 13, 'par' => 4, 'length_ft' => 505],
                            ['number' => 14, 'par' => 3, 'length_ft' => 295],
                            ['number' => 15, 'par' => 3, 'length_ft' => 284],
                            ['number' => 16, 'par' => 4, 'length_ft' => 418],
                            ['number' => 17, 'par' => 3, 'length_ft' => 439],
                            ['number' => 18, 'par' => 3, 'length_ft' => 327],
                        ],
                    ],
                    [
                        'name' => 'Tautas Klase',
                        'holes_count' => 18,
                        'par' => 60,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 161],
                            ['number' => 2, 'par' => 3, 'length_ft' => 257],
                            ['number' => 3, 'par' => 3, 'length_ft' => 200],
                            ['number' => 4, 'par' => 3, 'length_ft' => 197],
                            ['number' => 5, 'par' => 5, 'length_ft' => 524],
                            ['number' => 6, 'par' => 4, 'length_ft' => 409],
                            ['number' => 7, 'par' => 4, 'length_ft' => 280],
                            ['number' => 8, 'par' => 3, 'length_ft' => 222],
                            ['number' => 9, 'par' => 3, 'length_ft' => 219],
                            ['number' => 10, 'par' => 3, 'length_ft' => 215],
                            ['number' => 11, 'par' => 3, 'length_ft' => 196],
                            ['number' => 12, 'par' => 3, 'length_ft' => 274],
                            ['number' => 13, 'par' => 3, 'length_ft' => 330],
                            ['number' => 14, 'par' => 3, 'length_ft' => 181],
                            ['number' => 15, 'par' => 3, 'length_ft' => 284],
                            ['number' => 16, 'par' => 5, 'length_ft' => 418],
                            ['number' => 17, 'par' => 3, 'length_ft' => 242],
                            ['number' => 18, 'par' => 3, 'length_ft' => 327],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'NRC "Vaivari" disku golfa parks',
                'lat' => 56.958700,
                'lon' => 23.668543,
                'address' => 'Jūrmala, Latvia',
                'locality' => 'Jūrmala',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/nrc-vaivari-disku-golfa-parks-cTZ0',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 9,
                        'par' => 27,
                        'length_ft' => 1042,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => null],
                            ['number' => 2, 'par' => 3, 'length_ft' => null],
                            ['number' => 3, 'par' => 3, 'length_ft' => null],
                            ['number' => 4, 'par' => 3, 'length_ft' => null],
                            ['number' => 5, 'par' => 3, 'length_ft' => null],
                            ['number' => 6, 'par' => 3, 'length_ft' => null],
                            ['number' => 7, 'par' => 3, 'length_ft' => null],
                            ['number' => 8, 'par' => 3, 'length_ft' => null],
                            ['number' => 9, 'par' => 3, 'length_ft' => null],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Kandavas Disku Golfs',
                'lat' => 57.043790,
                'lon' => 22.779928,
                'address' => 'Pūzurgravas iela 2, Kandava, Tukuma novads, LV-3120, Latvia',
                'locality' => 'Kandava',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/kandavas-diksu-golfs-7LTD',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 9,
                        'par' => 28,
                        'length_ft' => 2596,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 255],
                            ['number' => 2, 'par' => 3, 'length_ft' => 248],
                            ['number' => 3, 'par' => 3, 'length_ft' => 279],
                            ['number' => 4, 'par' => 3, 'length_ft' => 234],
                            ['number' => 5, 'par' => 3, 'length_ft' => 272],
                            ['number' => 6, 'par' => 3, 'length_ft' => 219],
                            ['number' => 7, 'par' => 3, 'length_ft' => 369],
                            ['number' => 8, 'par' => 3, 'length_ft' => 256],
                            ['number' => 9, 'par' => 4, 'length_ft' => 464],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Ventspils Disku Golfa Parks',
                'lat' => 57.374132,
                'lon' => 21.543880,
                'address' => 'Ventspils, Latvia',
                'locality' => 'Ventspils',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/ventspils-disku-golfa-parks-51Ia',
                'layouts' => [
                    [
                        'name' => 'Lielais aplis',
                        'holes_count' => 18,
                        'par' => 61,
                        'length_ft' => 6782,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 253],
                            ['number' => 2, 'par' => 3, 'length_ft' => 246],
                            ['number' => 3, 'par' => 3, 'length_ft' => 289],
                            ['number' => 4, 'par' => 3, 'length_ft' => 295],
                            ['number' => 5, 'par' => 4, 'length_ft' => 548],
                            ['number' => 6, 'par' => 3, 'length_ft' => 217],
                            ['number' => 7, 'par' => 3, 'length_ft' => 328],
                            ['number' => 8, 'par' => 4, 'length_ft' => 659],
                            ['number' => 9, 'par' => 3, 'length_ft' => 295],
                            ['number' => 10, 'par' => 3, 'length_ft' => 226],
                            ['number' => 11, 'par' => 5, 'length_ft' => 804],
                            ['number' => 12, 'par' => 3, 'length_ft' => 262],
                            ['number' => 13, 'par' => 4, 'length_ft' => 482],
                            ['number' => 14, 'par' => 3, 'length_ft' => 289],
                            ['number' => 15, 'par' => 4, 'length_ft' => 443],
                            ['number' => 16, 'par' => 4, 'length_ft' => 486],
                            ['number' => 17, 'par' => 3, 'length_ft' => 358],
                            ['number' => 18, 'par' => 3, 'length_ft' => 302],
                        ],
                    ],
                    [
                        'name' => 'Mazais aplis',
                        'holes_count' => 9,
                        'par' => 29,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => null],
                            ['number' => 2, 'par' => 3, 'length_ft' => null],
                            ['number' => 3, 'par' => 3, 'length_ft' => null],
                            ['number' => 4, 'par' => 3, 'length_ft' => null],
                            ['number' => 5, 'par' => 4, 'length_ft' => null],
                            ['number' => 6, 'par' => 3, 'length_ft' => null],
                            ['number' => 7, 'par' => 4, 'length_ft' => null],
                            ['number' => 8, 'par' => 3, 'length_ft' => null],
                            ['number' => 9, 'par' => 3, 'length_ft' => null],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Sabiles graviņas disku golfa parks',
                'lat' => 57.049377,
                'lon' => 22.579949,
                'address' => 'Priedes, Sabile, Talsu novads, Latvia',
                'locality' => 'Sabile',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/sabiles-garvinas-disku-gofa-parks-QreS',
                'note' => 'Listed as possibly permanently closed / relocated on UDisc as of this research.',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 9,
                        'par' => 28,
                        'length_ft' => 2291,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 288],
                            ['number' => 2, 'par' => 3, 'length_ft' => 169],
                            ['number' => 3, 'par' => 3, 'length_ft' => 202],
                            ['number' => 4, 'par' => 3, 'length_ft' => 235],
                            ['number' => 5, 'par' => 4, 'length_ft' => 392],
                            ['number' => 6, 'par' => 3, 'length_ft' => 250],
                            ['number' => 7, 'par' => 3, 'length_ft' => 285],
                            ['number' => 8, 'par' => 3, 'length_ft' => 179],
                            ['number' => 9, 'par' => 3, 'length_ft' => 291],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Deviņkalnu disku golfa parks',
                'lat' => 57.238512,
                'lon' => 22.598262,
                'address' => 'Talsi, Latvia',
                'locality' => 'Talsi',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/devinnkalnu-disku-golfa-parks-FujD',
                'layouts' => [
                    [
                        'name' => 'Silver',
                        'holes_count' => 18,
                        'par' => 71,
                        'length_ft' => 8725,
                        'holes' => [
                            ['number' => 1, 'par' => 5, 'length_ft' => 591],
                            ['number' => 2, 'par' => 4, 'length_ft' => 436],
                            ['number' => 3, 'par' => 5, 'length_ft' => 682],
                            ['number' => 4, 'par' => 3, 'length_ft' => 262],
                            ['number' => 5, 'par' => 3, 'length_ft' => 269],
                            ['number' => 6, 'par' => 3, 'length_ft' => 299],
                            ['number' => 7, 'par' => 5, 'length_ft' => 650],
                            ['number' => 8, 'par' => 4, 'length_ft' => 646],
                            ['number' => 9, 'par' => 3, 'length_ft' => 289],
                            ['number' => 10, 'par' => 3, 'length_ft' => 220],
                            ['number' => 11, 'par' => 5, 'length_ft' => 869],
                            ['number' => 12, 'par' => 4, 'length_ft' => 630],
                            ['number' => 13, 'par' => 4, 'length_ft' => 673],
                            ['number' => 14, 'par' => 5, 'length_ft' => 663],
                            ['number' => 15, 'par' => 3, 'length_ft' => 420],
                            ['number' => 16, 'par' => 3, 'length_ft' => 230],
                            ['number' => 17, 'par' => 5, 'length_ft' => 535],
                            ['number' => 18, 'par' => 4, 'length_ft' => 361],
                        ],
                    ],
                    [
                        'name' => 'Blue layout',
                        'holes_count' => 18,
                        'par' => 54,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 591],
                            ['number' => 2, 'par' => 3, 'length_ft' => 436],
                            ['number' => 3, 'par' => 3, 'length_ft' => 682],
                            ['number' => 4, 'par' => 3, 'length_ft' => 262],
                            ['number' => 5, 'par' => 3, 'length_ft' => 269],
                            ['number' => 6, 'par' => 3, 'length_ft' => 299],
                            ['number' => 7, 'par' => 3, 'length_ft' => 650],
                            ['number' => 8, 'par' => 3, 'length_ft' => 646],
                            ['number' => 9, 'par' => 3, 'length_ft' => 289],
                            ['number' => 10, 'par' => 3, 'length_ft' => 220],
                            ['number' => 11, 'par' => 3, 'length_ft' => 869],
                            ['number' => 12, 'par' => 3, 'length_ft' => 630],
                            ['number' => 13, 'par' => 3, 'length_ft' => 673],
                            ['number' => 14, 'par' => 3, 'length_ft' => 663],
                            ['number' => 15, 'par' => 3, 'length_ft' => 420],
                            ['number' => 16, 'par' => 3, 'length_ft' => 230],
                            ['number' => 17, 'par' => 3, 'length_ft' => 535],
                            ['number' => 18, 'par' => 3, 'length_ft' => 361],
                        ],
                    ],
                    [
                        'name' => 'Gold layout',
                        'holes_count' => 18,
                        'par' => 64,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 591],
                            ['number' => 2, 'par' => 4, 'length_ft' => 436],
                            ['number' => 3, 'par' => 4, 'length_ft' => 682],
                            ['number' => 4, 'par' => 3, 'length_ft' => 262],
                            ['number' => 5, 'par' => 3, 'length_ft' => 269],
                            ['number' => 6, 'par' => 3, 'length_ft' => 299],
                            ['number' => 7, 'par' => 5, 'length_ft' => 650],
                            ['number' => 8, 'par' => 4, 'length_ft' => 646],
                            ['number' => 9, 'par' => 3, 'length_ft' => 289],
                            ['number' => 10, 'par' => 3, 'length_ft' => 220],
                            ['number' => 11, 'par' => 4, 'length_ft' => 869],
                            ['number' => 12, 'par' => 4, 'length_ft' => 630],
                            ['number' => 13, 'par' => 4, 'length_ft' => 673],
                            ['number' => 14, 'par' => 4, 'length_ft' => 663],
                            ['number' => 15, 'par' => 3, 'length_ft' => 420],
                            ['number' => 16, 'par' => 3, 'length_ft' => 230],
                            ['number' => 17, 'par' => 4, 'length_ft' => 535],
                            ['number' => 18, 'par' => 3, 'length_ft' => 361],
                        ],
                    ],
                    [
                        'name' => 'Deviņkalnu Beginner Layout',
                        'holes_count' => 9,
                        'par' => 36,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 5, 'length_ft' => 663],
                            ['number' => 2, 'par' => 3, 'length_ft' => 420],
                            ['number' => 3, 'par' => 3, 'length_ft' => 230],
                            ['number' => 4, 'par' => 5, 'length_ft' => 535],
                            ['number' => 5, 'par' => 3, 'length_ft' => 361],
                            ['number' => 6, 'par' => 5, 'length_ft' => 591],
                            ['number' => 7, 'par' => 4, 'length_ft' => 436],
                            ['number' => 8, 'par' => 5, 'length_ft' => 682],
                            ['number' => 9, 'par' => 3, 'length_ft' => 262],
                        ],
                    ],
                    [
                        'name' => 'Main',
                        'holes_count' => 19,
                        'par' => 73,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 5, 'length_ft' => 663],
                            ['number' => 2, 'par' => 3, 'length_ft' => 420],
                            ['number' => 3, 'par' => 3, 'length_ft' => 230],
                            ['number' => 4, 'par' => 5, 'length_ft' => 535],
                            ['number' => 5, 'par' => 3, 'length_ft' => 361],
                            ['number' => 6, 'par' => 5, 'length_ft' => 591],
                            ['number' => 7, 'par' => 4, 'length_ft' => 436],
                            ['number' => 8, 'par' => 5, 'length_ft' => 682],
                            ['number' => 9, 'par' => 3, 'length_ft' => 262],
                            ['number' => 10, 'par' => 3, 'length_ft' => 269],
                            ['number' => 11, 'par' => 3, 'length_ft' => 299],
                            ['number' => 12, 'par' => 5, 'length_ft' => 650],
                            ['number' => 13, 'par' => 4, 'length_ft' => 646],
                            ['number' => 14, 'par' => 3, 'length_ft' => 289],
                            ['number' => 15, 'par' => 3, 'length_ft' => 220],
                            ['number' => 16, 'par' => 3, 'length_ft' => 220],
                            ['number' => 17, 'par' => 5, 'length_ft' => 869],
                            ['number' => 18, 'par' => 4, 'length_ft' => 630],
                            ['number' => 19, 'par' => 4, 'length_ft' => 673],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Inčukalna Medību Pils Laukums',
                'lat' => 57.127984,
                'lon' => 24.632014,
                'address' => 'Kārļzemnieki, Latvia',
                'locality' => 'Inčukalns',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/incukalna-medibu-pils-laukums-VmoO',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 18,
                        'par' => 56,
                        'length_ft' => 5006,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 249],
                            ['number' => 2, 'par' => 3, 'length_ft' => 236],
                            ['number' => 3, 'par' => 3, 'length_ft' => 243],
                            ['number' => 4, 'par' => 3, 'length_ft' => 262],
                            ['number' => 5, 'par' => 3, 'length_ft' => 249],
                            ['number' => 6, 'par' => 3, 'length_ft' => 302],
                            ['number' => 7, 'par' => 3, 'length_ft' => 269],
                            ['number' => 8, 'par' => 3, 'length_ft' => 259],
                            ['number' => 9, 'par' => 3, 'length_ft' => 246],
                            ['number' => 10, 'par' => 4, 'length_ft' => 400],
                            ['number' => 11, 'par' => 3, 'length_ft' => 226],
                            ['number' => 12, 'par' => 3, 'length_ft' => 246],
                            ['number' => 13, 'par' => 3, 'length_ft' => 184],
                            ['number' => 14, 'par' => 3, 'length_ft' => 272],
                            ['number' => 15, 'par' => 3, 'length_ft' => 325],
                            ['number' => 16, 'par' => 3, 'length_ft' => 276],
                            ['number' => 17, 'par' => 3, 'length_ft' => 240],
                            ['number' => 18, 'par' => 4, 'length_ft' => 522],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Limbo disku golfa parks',
                'lat' => 57.502856,
                'lon' => 24.705413,
                'address' => 'Limbaži, Latvia',
                'locality' => 'Limbaži',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/limbo-disc-golf-course-3fbo',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 18,
                        'par' => 58,
                        'length_ft' => 6170,
                        'holes' => [
                            ['number' => 1, 'par' => 4, 'length_ft' => 561],
                            ['number' => 2, 'par' => 4, 'length_ft' => 433],
                            ['number' => 3, 'par' => 4, 'length_ft' => 512],
                            ['number' => 4, 'par' => 3, 'length_ft' => 348],
                            ['number' => 5, 'par' => 3, 'length_ft' => 272],
                            ['number' => 6, 'par' => 4, 'length_ft' => 541],
                            ['number' => 7, 'par' => 3, 'length_ft' => 279],
                            ['number' => 8, 'par' => 3, 'length_ft' => 312],
                            ['number' => 9, 'par' => 3, 'length_ft' => 276],
                            ['number' => 10, 'par' => 3, 'length_ft' => 400],
                            ['number' => 11, 'par' => 3, 'length_ft' => 240],
                            ['number' => 12, 'par' => 3, 'length_ft' => 220],
                            ['number' => 13, 'par' => 3, 'length_ft' => 240],
                            ['number' => 14, 'par' => 3, 'length_ft' => 213],
                            ['number' => 15, 'par' => 3, 'length_ft' => 338],
                            ['number' => 16, 'par' => 3, 'length_ft' => 322],
                            ['number' => 17, 'par' => 3, 'length_ft' => 292],
                            ['number' => 18, 'par' => 3, 'length_ft' => 371],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Salaspils Ako',
                'lat' => 56.843738,
                'lon' => 24.387329,
                'address' => 'Saulkalne, Salaspils novads, Latvia',
                'locality' => 'Salaspils',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/salaspils-ako-RIwQ',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 18,
                        'par' => 58,
                        'length_ft' => 5887,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 340],
                            ['number' => 2, 'par' => 3, 'length_ft' => 241],
                            ['number' => 3, 'par' => 3, 'length_ft' => 155],
                            ['number' => 4, 'par' => 4, 'length_ft' => 478],
                            ['number' => 5, 'par' => 4, 'length_ft' => 492],
                            ['number' => 6, 'par' => 3, 'length_ft' => 279],
                            ['number' => 7, 'par' => 3, 'length_ft' => 287],
                            ['number' => 8, 'par' => 3, 'length_ft' => 232],
                            ['number' => 9, 'par' => 4, 'length_ft' => 488],
                            ['number' => 10, 'par' => 3, 'length_ft' => 256],
                            ['number' => 11, 'par' => 3, 'length_ft' => 214],
                            ['number' => 12, 'par' => 4, 'length_ft' => 513],
                            ['number' => 13, 'par' => 3, 'length_ft' => 256],
                            ['number' => 14, 'par' => 3, 'length_ft' => 315],
                            ['number' => 15, 'par' => 3, 'length_ft' => 277],
                            ['number' => 16, 'par' => 3, 'length_ft' => 327],
                            ['number' => 17, 'par' => 3, 'length_ft' => 325],
                            ['number' => 18, 'par' => 3, 'length_ft' => 412],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Zaķumuižas Disku Golfa Parks',
                'lat' => 56.969961,
                'lon' => 24.489967,
                'address' => 'Zaķumuiža, Latvia',
                'locality' => 'Zaķumuiža',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/zakumuizas-disku-golfa-parks-di5t',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 9,
                        'par' => 27,
                        'length_ft' => 2189,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 174],
                            ['number' => 2, 'par' => 3, 'length_ft' => 236],
                            ['number' => 3, 'par' => 3, 'length_ft' => 214],
                            ['number' => 4, 'par' => 3, 'length_ft' => 169],
                            ['number' => 5, 'par' => 3, 'length_ft' => 303],
                            ['number' => 6, 'par' => 3, 'length_ft' => 209],
                            ['number' => 7, 'par' => 3, 'length_ft' => 325],
                            ['number' => 8, 'par' => 3, 'length_ft' => 201],
                            ['number' => 9, 'par' => 3, 'length_ft' => 358],
                        ],
                    ],
                    [
                        'name' => '2x9',
                        'holes_count' => 18,
                        'par' => 54,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 175],
                            ['number' => 2, 'par' => 3, 'length_ft' => 269],
                            ['number' => 3, 'par' => 3, 'length_ft' => 208],
                            ['number' => 4, 'par' => 3, 'length_ft' => 214],
                            ['number' => 5, 'par' => 3, 'length_ft' => 285],
                            ['number' => 6, 'par' => 3, 'length_ft' => 228],
                            ['number' => 7, 'par' => 3, 'length_ft' => 330],
                            ['number' => 8, 'par' => 3, 'length_ft' => 190],
                            ['number' => 9, 'par' => 3, 'length_ft' => 411],
                            ['number' => 10, 'par' => 3, 'length_ft' => null],
                            ['number' => 11, 'par' => 3, 'length_ft' => null],
                            ['number' => 12, 'par' => 3, 'length_ft' => null],
                            ['number' => 13, 'par' => 3, 'length_ft' => null],
                            ['number' => 14, 'par' => 3, 'length_ft' => null],
                            ['number' => 15, 'par' => 3, 'length_ft' => null],
                            ['number' => 16, 'par' => 3, 'length_ft' => null],
                            ['number' => 17, 'par' => 3, 'length_ft' => null],
                            ['number' => 18, 'par' => 3, 'length_ft' => null],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Ķeguma Skolas Disc Golf Park',
                'lat' => 56.747073,
                'lon' => 24.714863,
                'address' => 'Ķegums, Ogres novads, Latvia',
                'locality' => 'Ķegums',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/keguma-skolas-disc-golf-park-85tE',
                'layouts' => [
                    [
                        'name' => 'Yellow DISCatcher Pro 24',
                        'holes_count' => 9,
                        'par' => 28,
                        'length_ft' => 2557,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 356],
                            ['number' => 2, 'par' => 3, 'length_ft' => 220],
                            ['number' => 3, 'par' => 3, 'length_ft' => 236],
                            ['number' => 4, 'par' => 4, 'length_ft' => 318],
                            ['number' => 5, 'par' => 3, 'length_ft' => 207],
                            ['number' => 6, 'par' => 3, 'length_ft' => 285],
                            ['number' => 7, 'par' => 3, 'length_ft' => 256],
                            ['number' => 8, 'par' => 3, 'length_ft' => 354],
                            ['number' => 9, 'par' => 3, 'length_ft' => 325],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Disku golfa parks Zibeņi',
                'lat' => 57.115379,
                'lon' => 24.292961,
                'address' => 'Carnikava, Latvia',
                'locality' => 'Carnikava',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/disku-golfa-parks-zibeni-f49p',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 18,
                        'par' => 60,
                        'length_ft' => 6789,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 284],
                            ['number' => 2, 'par' => 3, 'length_ft' => 267],
                            ['number' => 3, 'par' => 3, 'length_ft' => 354],
                            ['number' => 4, 'par' => 3, 'length_ft' => 223],
                            ['number' => 5, 'par' => 3, 'length_ft' => 331],
                            ['number' => 6, 'par' => 3, 'length_ft' => 328],
                            ['number' => 7, 'par' => 3, 'length_ft' => 239],
                            ['number' => 8, 'par' => 4, 'length_ft' => 521],
                            ['number' => 9, 'par' => 3, 'length_ft' => 332],
                            ['number' => 10, 'par' => 3, 'length_ft' => 424],
                            ['number' => 11, 'par' => 3, 'length_ft' => 283],
                            ['number' => 12, 'par' => 3, 'length_ft' => 318],
                            ['number' => 13, 'par' => 4, 'length_ft' => 416],
                            ['number' => 14, 'par' => 4, 'length_ft' => 463],
                            ['number' => 15, 'par' => 4, 'length_ft' => 462],
                            ['number' => 16, 'par' => 3, 'length_ft' => 367],
                            ['number' => 17, 'par' => 4, 'length_ft' => 522],
                            ['number' => 18, 'par' => 4, 'length_ft' => 655],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Tukuma disku golfa parks',
                'lat' => 56.966405,
                'lon' => 23.134847,
                'address' => 'Gotlandes iela 1, Tukums, Tukuma novads, LV-3101, Latvia',
                'locality' => 'Tukums',
                'country_code' => 'LV',
                'source' => 'DiscGolfMetrix / PDGA (UDisc has no published scorecard)',
                'source_url' => 'https://udisc.com/courses/tukuma-disku-golfa-parks-1P4L',
                'note' => 'UDisc has zero published layouts for this course (confirmed via its own layoutCount metadata) and its stray holeCount field says 15, conflicting with the 18-hole/par-62 figure sourced from DiscGolfMetrix league play. Treat this entry with lower confidence than the others.',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 18,
                        'par' => 62,
                        'length_ft' => 6624,
                        'holes' => [
                            ['number' => 1, 'par' => 4, 'length_ft' => null],
                            ['number' => 2, 'par' => 4, 'length_ft' => null],
                            ['number' => 3, 'par' => 4, 'length_ft' => null],
                            ['number' => 4, 'par' => 3, 'length_ft' => null],
                            ['number' => 5, 'par' => 3, 'length_ft' => null],
                            ['number' => 6, 'par' => 4, 'length_ft' => null],
                            ['number' => 7, 'par' => 3, 'length_ft' => null],
                            ['number' => 8, 'par' => 3, 'length_ft' => null],
                            ['number' => 9, 'par' => 3, 'length_ft' => null],
                            ['number' => 10, 'par' => 3, 'length_ft' => null],
                            ['number' => 11, 'par' => 3, 'length_ft' => null],
                            ['number' => 12, 'par' => 3, 'length_ft' => null],
                            ['number' => 13, 'par' => 3, 'length_ft' => null],
                            ['number' => 14, 'par' => 4, 'length_ft' => null],
                            ['number' => 15, 'par' => 3, 'length_ft' => null],
                            ['number' => 16, 'par' => 3, 'length_ft' => null],
                            ['number' => 17, 'par' => 4, 'length_ft' => null],
                            ['number' => 18, 'par' => 5, 'length_ft' => null],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Ikšķiles disku golfa parks',
                'lat' => 56.830092,
                'lon' => 24.504876,
                'address' => 'Ikšķile, Latvia',
                'locality' => 'Ikšķile',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/ikskiles-disku-golfa-parks-mIHa',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 9,
                        'par' => 28,
                        'length_ft' => 2512,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 205],
                            ['number' => 2, 'par' => 3, 'length_ft' => 195],
                            ['number' => 3, 'par' => 3, 'length_ft' => 266],
                            ['number' => 4, 'par' => 4, 'length_ft' => 504],
                            ['number' => 5, 'par' => 3, 'length_ft' => 314],
                            ['number' => 6, 'par' => 3, 'length_ft' => 184],
                            ['number' => 7, 'par' => 3, 'length_ft' => 408],
                            ['number' => 8, 'par' => 3, 'length_ft' => 220],
                            ['number' => 9, 'par' => 3, 'length_ft' => 216],
                        ],
                    ],
                    [
                        'name' => '2x9',
                        'holes_count' => 18,
                        'par' => 56,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => null],
                            ['number' => 2, 'par' => 3, 'length_ft' => null],
                            ['number' => 3, 'par' => 3, 'length_ft' => null],
                            ['number' => 4, 'par' => 4, 'length_ft' => null],
                            ['number' => 5, 'par' => 3, 'length_ft' => null],
                            ['number' => 6, 'par' => 3, 'length_ft' => null],
                            ['number' => 7, 'par' => 3, 'length_ft' => null],
                            ['number' => 8, 'par' => 3, 'length_ft' => null],
                            ['number' => 9, 'par' => 3, 'length_ft' => null],
                            ['number' => 10, 'par' => 3, 'length_ft' => null],
                            ['number' => 11, 'par' => 3, 'length_ft' => null],
                            ['number' => 12, 'par' => 3, 'length_ft' => null],
                            ['number' => 13, 'par' => 4, 'length_ft' => null],
                            ['number' => 14, 'par' => 3, 'length_ft' => null],
                            ['number' => 15, 'par' => 3, 'length_ft' => null],
                            ['number' => 16, 'par' => 3, 'length_ft' => null],
                            ['number' => 17, 'par' => 3, 'length_ft' => null],
                            ['number' => 18, 'par' => 3, 'length_ft' => null],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Disc Golf Park "Pauku Priedes"',
                'lat' => 57.531156,
                'lon' => 25.434848,
                'address' => 'Valmiera, Latvia',
                'locality' => 'Valmiera',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/disc-golf-park-pauku-priedes-Z86e',
                'layouts' => [
                    [
                        'name' => 'Yellow 19 (Dzeltens)',
                        'holes_count' => 19,
                        'par' => 62,
                        'length_ft' => 5806,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 274],
                            ['number' => 2, 'par' => 3, 'length_ft' => 326],
                            ['number' => 3, 'par' => 3, 'length_ft' => 213],
                            ['number' => 4, 'par' => 4, 'length_ft' => 564],
                            ['number' => 5, 'par' => 3, 'length_ft' => 269],
                            ['number' => 6, 'par' => 3, 'length_ft' => 245],
                            ['number' => 7, 'par' => 3, 'length_ft' => 205],
                            ['number' => 8, 'par' => 3, 'length_ft' => 245],
                            ['number' => 9, 'par' => 3, 'length_ft' => 243],
                            ['number' => 10, 'par' => 4, 'length_ft' => 416],
                            ['number' => 11, 'par' => 3, 'length_ft' => 215],
                            ['number' => 12, 'par' => 3, 'length_ft' => 306],
                            ['number' => 13, 'par' => 5, 'length_ft' => 632],
                            ['number' => 14, 'par' => 3, 'length_ft' => 243],
                            ['number' => 15, 'par' => 3, 'length_ft' => 220],
                            ['number' => 16, 'par' => 3, 'length_ft' => 209],
                            ['number' => 17, 'par' => 4, 'length_ft' => 419],
                            ['number' => 18, 'par' => 3, 'length_ft' => 359],
                            ['number' => 19, 'par' => 3, 'length_ft' => 203],
                        ],
                    ],
                    [
                        'name' => 'Blue 19 (Zils) PRO',
                        'holes_count' => 19,
                        'par' => 64,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 335],
                            ['number' => 2, 'par' => 4, 'length_ft' => 696],
                            ['number' => 3, 'par' => 3, 'length_ft' => 317],
                            ['number' => 4, 'par' => 4, 'length_ft' => 687],
                            ['number' => 5, 'par' => 3, 'length_ft' => 324],
                            ['number' => 6, 'par' => 3, 'length_ft' => 261],
                            ['number' => 7, 'par' => 3, 'length_ft' => 247],
                            ['number' => 8, 'par' => 3, 'length_ft' => 352],
                            ['number' => 9, 'par' => 4, 'length_ft' => 425],
                            ['number' => 10, 'par' => 4, 'length_ft' => 562],
                            ['number' => 11, 'par' => 3, 'length_ft' => 326],
                            ['number' => 12, 'par' => 3, 'length_ft' => 306],
                            ['number' => 13, 'par' => 5, 'length_ft' => 890],
                            ['number' => 14, 'par' => 3, 'length_ft' => 322],
                            ['number' => 15, 'par' => 3, 'length_ft' => 307],
                            ['number' => 16, 'par' => 3, 'length_ft' => 209],
                            ['number' => 17, 'par' => 4, 'length_ft' => 613],
                            ['number' => 18, 'par' => 3, 'length_ft' => 449],
                            ['number' => 19, 'par' => 3, 'length_ft' => 251],
                        ],
                    ],
                    [
                        'name' => 'Red 19 (Sarkans)',
                        'holes_count' => 19,
                        'par' => 64,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 192],
                            ['number' => 2, 'par' => 4, 'length_ft' => 490],
                            ['number' => 3, 'par' => 3, 'length_ft' => 153],
                            ['number' => 4, 'par' => 3, 'length_ft' => 284],
                            ['number' => 5, 'par' => 3, 'length_ft' => 183],
                            ['number' => 6, 'par' => 3, 'length_ft' => 176],
                            ['number' => 7, 'par' => 3, 'length_ft' => 163],
                            ['number' => 8, 'par' => 3, 'length_ft' => 197],
                            ['number' => 9, 'par' => 3, 'length_ft' => 243],
                            ['number' => 10, 'par' => 4, 'length_ft' => 296],
                            ['number' => 11, 'par' => 4, 'length_ft' => 326],
                            ['number' => 12, 'par' => 3, 'length_ft' => 306],
                            ['number' => 13, 'par' => 4, 'length_ft' => 480],
                            ['number' => 14, 'par' => 4, 'length_ft' => 322],
                            ['number' => 15, 'par' => 4, 'length_ft' => 307],
                            ['number' => 16, 'par' => 3, 'length_ft' => 209],
                            ['number' => 17, 'par' => 3, 'length_ft' => 214],
                            ['number' => 18, 'par' => 3, 'length_ft' => 242],
                            ['number' => 19, 'par' => 4, 'length_ft' => 251],
                        ],
                    ],
                    [
                        'name' => '2026 AmTour BLUE (4,13,17)',
                        'holes_count' => 19,
                        'par' => 64,
                        'length_ft' => null,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 335],
                            ['number' => 2, 'par' => 4, 'length_ft' => 696],
                            ['number' => 3, 'par' => 3, 'length_ft' => 317],
                            ['number' => 4, 'par' => 4, 'length_ft' => 564],
                            ['number' => 5, 'par' => 3, 'length_ft' => 324],
                            ['number' => 6, 'par' => 3, 'length_ft' => 261],
                            ['number' => 7, 'par' => 3, 'length_ft' => 247],
                            ['number' => 8, 'par' => 3, 'length_ft' => 352],
                            ['number' => 9, 'par' => 4, 'length_ft' => 425],
                            ['number' => 10, 'par' => 4, 'length_ft' => 562],
                            ['number' => 11, 'par' => 3, 'length_ft' => 326],
                            ['number' => 12, 'par' => 3, 'length_ft' => 306],
                            ['number' => 13, 'par' => 5, 'length_ft' => 632],
                            ['number' => 14, 'par' => 3, 'length_ft' => 322],
                            ['number' => 15, 'par' => 3, 'length_ft' => 307],
                            ['number' => 16, 'par' => 3, 'length_ft' => 209],
                            ['number' => 17, 'par' => 4, 'length_ft' => 419],
                            ['number' => 18, 'par' => 3, 'length_ft' => 449],
                            ['number' => 19, 'par' => 3, 'length_ft' => 251],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'UFO GOLF',
                'lat' => 57.012551,
                'lon' => 24.153969,
                'address' => 'Rīga, Latvia',
                'locality' => 'Rīga',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/ufo-golf-0qyn',
                'note' => 'Listed as permanently closed on UDisc as of this research.',
                'layouts' => [
                    [
                        'name' => 'UfoGolf - Lielais Laukums',
                        'holes_count' => 19,
                        'par' => 60,
                        'length_ft' => 5986,
                        'holes' => [
                            ['number' => 1, 'par' => 4, 'length_ft' => 565],
                            ['number' => 2, 'par' => 3, 'length_ft' => 219],
                            ['number' => 3, 'par' => 3, 'length_ft' => 221],
                            ['number' => 4, 'par' => 3, 'length_ft' => 236],
                            ['number' => 5, 'par' => 3, 'length_ft' => 266],
                            ['number' => 6, 'par' => 3, 'length_ft' => 343],
                            ['number' => 7, 'par' => 3, 'length_ft' => 280],
                            ['number' => 8, 'par' => 3, 'length_ft' => 337],
                            ['number' => 9, 'par' => 3, 'length_ft' => 255],
                            ['number' => 10, 'par' => 3, 'length_ft' => 188],
                            ['number' => 11, 'par' => 4, 'length_ft' => 575],
                            ['number' => 12, 'par' => 3, 'length_ft' => 488],
                            ['number' => 13, 'par' => 3, 'length_ft' => 300],
                            ['number' => 14, 'par' => 3, 'length_ft' => 343],
                            ['number' => 15, 'par' => 3, 'length_ft' => 225],
                            ['number' => 16, 'par' => 3, 'length_ft' => 174],
                            ['number' => 17, 'par' => 3, 'length_ft' => 219],
                            ['number' => 18, 'par' => 3, 'length_ft' => 256],
                            ['number' => 19, 'par' => 4, 'length_ft' => 496],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'PROPARK Disku golfa parks Baložos',
                'lat' => 56.879276,
                'lon' => 24.121485,
                'address' => 'Baloži, Latvia',
                'locality' => 'Baloži',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/propark-disku-golfa-parks-balozos-r4sY',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 18,
                        'par' => 58,
                        'length_ft' => 5437,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 224],
                            ['number' => 2, 'par' => 3, 'length_ft' => 266],
                            ['number' => 3, 'par' => 3, 'length_ft' => 338],
                            ['number' => 4, 'par' => 4, 'length_ft' => 380],
                            ['number' => 5, 'par' => 3, 'length_ft' => 305],
                            ['number' => 6, 'par' => 3, 'length_ft' => 244],
                            ['number' => 7, 'par' => 4, 'length_ft' => 459],
                            ['number' => 8, 'par' => 3, 'length_ft' => 234],
                            ['number' => 9, 'par' => 3, 'length_ft' => 247],
                            ['number' => 10, 'par' => 3, 'length_ft' => 271],
                            ['number' => 11, 'par' => 3, 'length_ft' => 217],
                            ['number' => 12, 'par' => 4, 'length_ft' => 592],
                            ['number' => 13, 'par' => 3, 'length_ft' => 200],
                            ['number' => 14, 'par' => 4, 'length_ft' => 383],
                            ['number' => 15, 'par' => 3, 'length_ft' => 216],
                            ['number' => 16, 'par' => 3, 'length_ft' => 288],
                            ['number' => 17, 'par' => 3, 'length_ft' => 276],
                            ['number' => 18, 'par' => 3, 'length_ft' => 297],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Riekstukalns',
                'lat' => 56.768799,
                'lon' => 24.403368,
                'address' => 'Baldones pagasts, Latvia',
                'locality' => 'Baldone',
                'country_code' => 'LV',
                'source' => 'UDisc',
                'source_url' => 'https://udisc.com/courses/riekstukalns-3gDW',
                'layouts' => [
                    [
                        'name' => 'Main',
                        'holes_count' => 18,
                        'par' => 58,
                        'length_ft' => 6752,
                        'holes' => [
                            ['number' => 1, 'par' => 3, 'length_ft' => 381],
                            ['number' => 2, 'par' => 4, 'length_ft' => 472],
                            ['number' => 3, 'par' => 3, 'length_ft' => 282],
                            ['number' => 4, 'par' => 3, 'length_ft' => 295],
                            ['number' => 5, 'par' => 3, 'length_ft' => 279],
                            ['number' => 6, 'par' => 3, 'length_ft' => 302],
                            ['number' => 7, 'par' => 3, 'length_ft' => 394],
                            ['number' => 8, 'par' => 3, 'length_ft' => 479],
                            ['number' => 9, 'par' => 4, 'length_ft' => 692],
                            ['number' => 10, 'par' => 4, 'length_ft' => 722],
                            ['number' => 11, 'par' => 3, 'length_ft' => 295],
                            ['number' => 12, 'par' => 3, 'length_ft' => 200],
                            ['number' => 13, 'par' => 3, 'length_ft' => 256],
                            ['number' => 14, 'par' => 3, 'length_ft' => 243],
                            ['number' => 15, 'par' => 3, 'length_ft' => 459],
                            ['number' => 16, 'par' => 4, 'length_ft' => 591],
                            ['number' => 17, 'par' => 3, 'length_ft' => 230],
                            ['number' => 18, 'par' => 3, 'length_ft' => 180],
                        ],
                    ],
                ],
            ],
        ];
    }

    public static function findNear(float $lat, float $lon, float $radiusKm = 1.0): ?array
    {
        $closest = null;
        $closestDistance = null;

        foreach (self::all() as $course) {
            $distance = self::distanceKm($lat, $lon, $course['lat'], $course['lon']);
            if ($distance <= $radiusKm && ($closestDistance === null || $distance < $closestDistance)) {
                $closest = $course;
                $closestDistance = $distance;
            }
        }

        return $closest;
    }

    public static function holeDetails(array $layout): array
    {
        return collect($layout['holes'])
            ->map(fn (array $hole) => [
                'number' => $hole['number'],
                'par' => $hole['par'],
                'length_m' => is_numeric($hole['length_ft'] ?? null) ? round($hole['length_ft'] * 0.3048) : null,
            ])
            ->values()
            ->all();
    }

    public static function layoutsForJson(array $course): array
    {
        return collect($course['layouts'])
            ->map(fn (array $layout) => [
                'name' => $layout['name'],
                'holes_count' => $layout['holes_count'],
                'par' => $layout['par'],
                'hole_details' => self::holeDetails($layout),
            ])
            ->values()
            ->all();
    }

    public static function distanceKm(float $lat1, float $lon1, float $lat2, float $lon2): float
    {
        $earthRadiusKm = 6371;
        $latDelta = deg2rad($lat2 - $lat1);
        $lonDelta = deg2rad($lon2 - $lon1);
        $a = sin($latDelta / 2) ** 2
            + cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * sin($lonDelta / 2) ** 2;

        return $earthRadiusKm * 2 * asin(min(1, sqrt($a)));
    }
}
